version: '3.8'

services:
  maven-parser:
    container_name: maven-parser
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 4000:4000

networks:
  default:
    external:
      name: proxynet